package de.erstihelfer.erstihelfer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-06-14T16:48:04.211+02:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "ErstiHelferOnlineIntegrationService", 
                  wsdlLocation = "http://localhost:8080/erstihelfer/ErstiHelferOnlineIntegration?wsdl",
                  targetNamespace = "http://erstihelfer.erstihelfer.de/") 
public class ErstiHelferOnlineIntegrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://erstihelfer.erstihelfer.de/", "ErstiHelferOnlineIntegrationService");
    public final static QName ErstiHelferOnlineIntegrationPort = new QName("http://erstihelfer.erstihelfer.de/", "ErstiHelferOnlineIntegrationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/erstihelfer/ErstiHelferOnlineIntegration?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ErstiHelferOnlineIntegrationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/erstihelfer/ErstiHelferOnlineIntegration?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ErstiHelferOnlineIntegrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ErstiHelferOnlineIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErstiHelferOnlineIntegrationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ErstiHelferOnlineIntegrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ErstiHelferOnlineIntegrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ErstiHelferOnlineIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ErstiHelferOnlineIntegration
     */
    @WebEndpoint(name = "ErstiHelferOnlineIntegrationPort")
    public ErstiHelferOnlineIntegration getErstiHelferOnlineIntegrationPort() {
        return super.getPort(ErstiHelferOnlineIntegrationPort, ErstiHelferOnlineIntegration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ErstiHelferOnlineIntegration
     */
    @WebEndpoint(name = "ErstiHelferOnlineIntegrationPort")
    public ErstiHelferOnlineIntegration getErstiHelferOnlineIntegrationPort(WebServiceFeature... features) {
        return super.getPort(ErstiHelferOnlineIntegrationPort, ErstiHelferOnlineIntegration.class, features);
    }

}
