package de.erstihelfer.erstihelfer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-06-07T16:09:55.019+02:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://erstihelfer.erstihelfer.de/", name = "ErstiHelferOnlineIntegration")
@XmlSeeAlso({ObjectFactory.class})
public interface ErstiHelferOnlineIntegration {

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://erstihelfer.erstihelfer.de/", className = "de.erstihelfer.erstihelfer.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://erstihelfer.erstihelfer.de/", className = "de.erstihelfer.erstihelfer.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.erstihelfer.erstihelfer.UserLoginResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "registerNewUser", targetNamespace = "http://erstihelfer.erstihelfer.de/", className = "de.erstihelfer.erstihelfer.RegisterNewUser")
    @ResponseWrapper(localName = "registerNewUserResponse", targetNamespace = "http://erstihelfer.erstihelfer.de/", className = "de.erstihelfer.erstihelfer.RegisterNewUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.erstihelfer.erstihelfer.UserLoginResponse registerNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://erstihelfer.erstihelfer.de/", className = "de.erstihelfer.erstihelfer.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://erstihelfer.erstihelfer.de/", className = "de.erstihelfer.erstihelfer.LogoutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.erstihelfer.erstihelfer.ReturnCodeResponse logout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
